// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgres://postgres:Bi8NfrrMJxIAh1riLc3JQht6XogOgiwxfcCJVxPp5pyJ0xQqez2rZReDK5jImiV1@wco75f8zg2sxqar5zy00wfet:5432/postgres",
  },
});
